#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')
URGENT_VALUE=2


# no colon
remaining="$(acpi | sed 's/.*\([0-9][0-9]\):\([0-9][0-9]\):\([0-9][0-9]\).*/\1\2\3/')"

# with colon
#remaining="$(acpi | sed 's/.*\([0-9][0-9]:[0-9][0-9]:[0-9][0-9]\).*/\1/')"  


if [[ "${BATTERY_STATE}" = "Full" ]]; then
  label="<span font='Font Awesome 5 Free Solid 11'></span>"
  sign=""
  remaining=""
else
  sign="<span font='Font Awesome 5 Free Solid 11'></span>"
  if [[ $BATTERY_POWER -lt 20 ]]; then
    label="<span font='Font Awesome 5 Free Solid 11'></span>"
  elif [[ $BATTERY_POWER -lt 45 ]]; then
    label="<span font='Font Awesome 5 Free Solid 11'></span>"
  elif [[ $BATTERY_POWER -lt 70 ]]; then
    label="<span font='Font Awesome 5 Free Solid 11'></span>"
  elif   [[ $BATTERY_POWER -lt 95 ]]; then
    label="<span font='Font Awesome 5 Free Solid 11'></span>"
  elif   [[ $BATTERY_POWER -ge 95 ]]; then
    label="<span font='Font Awesome 5 Free Solid 11'></span>"
  fi
fi

  echo "$label ${BATTERY_POWER}% $sign $remaining"
  echo "$label ${BATTERY_POWER}%"
 


if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
