#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

URGENT_VALUE=10

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  sign="+"
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
  sign="-"
else
  sign=""
fi




label="<span font='Font Awesome 5 Free Solid 11'> </span>"
  echo "$label${BATTERY_POWER}%$sign"
  echo "$label${BATTERY_POWER}%$sign"
 


if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
