#!/bin/bash

# Adds support for cmus in i3 bar
# Modified from Yash Srivastav's by Marcos Conceição


stat=$(cmus-remote -Q 2> /dev/null | grep status | cut -d ' ' -f2-)
duration=$(cmus-remote -Q 2> /dev/null | grep duration | cut -d ' ' -f2-)
current=$(cmus-remote -Q 2> /dev/null | grep position | cut -d ' ' -f2-)
artist=$(cmus-remote -Q 2> /dev/null | grep ' artist ' | cut -d ' ' -f3-)
song=$(cmus-remote -Q 2> /dev/null | grep title | cut -d ' ' -f3-)
label="<span font='Font Awesome 5 Free Solid 11'> </span>"
if [[ "$stat" != "" && "$artist" != "" && "$stat" != "paused" ]]; then
  echo $label"$artist - $song $current / $duration"
  echo $label"$song"
  if [[ "$stat" == "playing" ]]; then
    echo "#B9CEFA"
  else
    echo "#FDB3BD"
  fi
fi

