#!/bin/bash

# For PulseAudio users, use "pulse"
# For Jack/Jack2 users, use "jackplug"
# For ALSA users, you may use "default" for your primary card

MIXER="default"
[ -n "$(lsmod | grep pulse)" ] && MIXER="pulse"
[ -n "$(lsmod | grep jack)" ] && MIXER="jackplug"
MIXER="${2:-$MIXER}"

SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols | sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" | head -n1 )}"


## The first parameter sets the step to change the volume by (and units to display)
## This may be in in % or dB (eg. 5% or 3dB)
STEP="${1:-5%}"
#

capability="$(amixer -D $MIXER get $SCONTROL | sed -n "s/  Capabilities:.*cvolume.*/Capture/p")"
# return "Capture" if it's a capture device

volume="$(amixer -D $MIXER get $SCONTROL ${capability})"

label="<span font='Font Awesome 5 Free Solid 11'> </span>"
volume="${volume%]*}"
stat="${volume##*[}"
if [ $stat = on ]
then
  volume="${volume%]*}"
  volume="${volume%]*}"
  volume="${volume##*[}"
else
  volume=""
fi

echo $label$volume

	



case $BLOCK_BUTTON in
  3) amixer -q -D $MIXER sset $SCONTROL $(capability) toggle ;;  # right click, mute/unmute
  4) amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}+ unmute ;; # scroll up, increase
  5) amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}- unmute ;; # scroll down, decrease
esac

#volume | format
