#!/bin/bash
# Modified from Alexander Keller's

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

label="<span font='Font Awesome 5 Free Solid 11'> </span>"
set $(iw dev wlp3s0 link | grep SSID | cut -d " " -f 2-)
# …
echo $label$1 $QUALITY%  # full text
echo $label$QUALITY%  # short text

# color
if [[ $QUALITY -lt 40 ]]; then
    echo "#B85C8C"
elif [[ $QUALITY -lt 60 ]]; then
    echo "#FDB3BD"
elif [[ $QUALITY -lt 80 ]]; then
    echo "#B9CEFA"
elif   [[ $QUALITY -ge 80 ]]; then
    echo "#FDF8F1"
fi


case $BLOCK_BUTTON in
  3) wicd-gtk  -n # right click, open wicd-gtk
esac

