#!/usr/bin/env sh

#
# Shell common environment variables and functions (BusyBox compatible)
#

export EDITOR="nvim"
export VISUAL="nvim"
export PAGER=less
export TERMINAL="st"
export FILEBROWSER="$TERMINAL -e vifm_ueberzug"
export BROWSER="qutebrowser"
export TRUEBROWSER="qutebrowser"
export MAIL="$HOME/.local/share/mail/main"  # mutt
export READER="zathura"
#export TERM=screen-256color

export INIT=$HOME/.config/nvim/init.vim

# Program-specific
export CALIBRE_USE_SYSTEM_THEME=1

# my preferences
export AURMANAGER="yay"
#export PODCASTS_RSS_FILE="$HOME/.config/mpd/podcasts_rss"

direnv() {  # environment variable name, path
    export "$1"="$2"
    mkdir -p "$2"
}

# Get out of my $HOME!
direnv CCACHE_BASEDIR "$HOME/.cache/ccache"
export CCACHE_CONFIGPATH="$HOME/.config/ccache.conf"
direnv GNUPGHOME "$HOME/.config/gnupg"
direnv GOPATH "$HOME/.cache/go"
export INPUTRC="$HOME/.config/inputrc"
export LESSHISTFILE="$HOME/.cache/lesshst"
direnv npm_config_cache "$HOME/.cache/npm"
export PYTHONSTARTUP="$HOME/.config/pythonstartup.py"
export SQLITE_HISTFILE="$HOME/.cache/sqlite_history"
export MYVIMRC="$HOME/.config/vim/vimrc"
#export VIMINIT="source $MYVIMRC"
direnv WINEPREFIX "$HOME/.cache/wineprefix/default"
#export TASKRC="$HOME/.config/taskrc"
#direnv TASKDATA "$HOME/.config/task"
#direnv TIMEWARRIORDB "$HOME/.config/timewarrior"
#export XAUTHORITY="$HOME/.config/Xauthority"  # seems not to work with lightdm

# And for the rest, see aliases
direnv JUNKHOME "$HOME/.cache/junkhome"

# For software that did not understand that XDG variables have defaults
direnv XDG_DATA_HOME "$HOME/.local/share"
direnv XDG_CONFIG_HOME "$HOME/.config"
export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
export XDG_CONFIG_DIRS="/etc/xdg"
direnv XDG_CACHE_HOME "$HOME/.cache"
direnv XDG_RUNTIME_DIR "$HOME/.local/run"
chmod 0700 "$XDG_RUNTIME_DIR"


# $PATH

# Function stolen from Arch Linux /etc/profile
appendpath() {
    if [ ! -d "$1" ]; then
        return
    fi
    case ":$PATH:" in
        *:"$1":*) ;;
        *) export PATH="${PATH:+$PATH:}$1" ;;
    esac
}

prependpath() {
    if [ ! -d "$1" ]; then
        return
    fi
    case ":$PATH:" in
        *:"$1":*) ;;
        *) export PATH="$1${PATH:+:$PATH}" ;;
    esac
}

prependpath "$HOME/.local/bin"
prependpath "$HOME/.local/bin/polybar"
prependpath "$HOME/.local/bin/i3bar"
prependpath "$HOME/.local/bin/menu"
appendpath "$HOME/.local/bin/podcast2playlist"

# python virtualenvwrapper
export WORKON_HOME=~/.virtualenvs
#export PIP_REQUIRE_VIRTUALENV=false

# Seimic Unix
export CWPROOT=/opt/SeisUnix
appendpath "$CWPROOT/bin"
