#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')
URGENT_VALUE=2


remaining=""
color=""
label="<span font='Font Awesome 5 Free Solid 11'></span>"
sign=" <span font='Font Awesome 5 Free Solid 11'></span> "

if [[ "${BATTERY_STATE}" != "Full" ]]; then
  # collonned timer
  #remaining="$(acpi | sed 's/.*\([0-9][0-9]:[0-9][0-9]:[0-9][0-9]\).*/\1/')"  

  # no colonned timer
  remaining=$sign"$(acpi | sed 's/.*\([0-9][0-9]\):\([0-9][0-9]\):\([0-9][0-9]\).*/\1\2\3/')"

  if [[ $BATTERY_POWER -lt 20 ]]; then
    label="<span font='Font Awesome 5 Free Solid 11'></span>"
  elif [[ $BATTERY_POWER -lt 45 ]]; then
    label="<span font='Font Awesome 5 Free Solid 11'></span>"
  elif [[ $BATTERY_POWER -lt 70 ]]; then
    label="<span font='Font Awesome 5 Free Solid 11'></span>"
  elif   [[ $BATTERY_POWER -lt 95 ]]; then
    label="<span font='Font Awesome 5 Free Solid 11'></span>"
    color=#FF0000
  elif   [[ $BATTERY_POWER -ge 95 ]]; then
    label="<span font='Font Awesome 5 Free Solid 11'></span>"
  fi
fi


  echo "$label ${BATTERY_POWER}%$remaining"
  echo "$label ${BATTERY_POWER}%"
 

if   [[ $BATTERY_POWER -lt 15 ]]; then
  if [[ "${BATTERY_STATE}" = "Discharging" ]]; then
    echo \#991510
    echo \#991510
  fi
fi


if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
