#!/bin/bash

label="<span font='Font Awesome 5 Free Solid 11'> </span>"


# working with xbacklight

echo $label$(xbacklight -get | cut --delimiter=. -f1)%
case $BLOCK_BUTTON in
  4) xbacklight -inc 10 ;; # scroll up, increase
  5) xbacklight -dec 10 ;; # scroll down, decrease
esac


# Working with xrandr

#max="$(cat /sys/class/backlight/*/max_brightness)"
#actual="$(cat /sys/class/backlight/intel_backlight/actual_brightness)"
#percent=$((100 * actual / max))
#echo $label$percent%
#step=10*$max/100


#case $BLOCK_BUTTON in
#  4) xrandr --output eDP-1-1 --brightness $(($actual+$step)) ;; # scroll up, increase
#  4) xrandr --output eDP-1-1 --brightness $(($actual-$step)) ;; # scroll down, decrease
#esac
