#!/bin/bash
font=$1
size=$2
bg=$3
fg=$4
choices="lock\nsuspend\nlogout\nshutdown\nreboot"
chosen=$(echo -e "$choices" | dmenu -nb "$bg" -nf "$fg" -sb "$fg" -sf $bg -i -p "power menu")

case "$chosen" in
  lock)     i3lock --color "$bg" ;;
  suspend)  sudo systemctl suspend ;;
  logout)   i3-msg exit ;;
  shutdown) sudo shutdown -h now ;;
  reboot)   sudo reboot ;;
esac
