#!/bin/sh

# Import the colors
. "${HOME}/.cache/wal/colors.sh"
# Import the fonts
symbol_font_name="$(xrdb -query | awk '$1~/^*symbol_font_name:$/ {$1=""; print $0}')"
# stopwatch 
# sandwatch 
label=""
fg=$background
bg=$foreground
sp=" "
full_text=""
short_text=""

cont="0"

while [ $cont -lt 5 ]
do
    echo $cont
    sleep 1
    let cont=cont+1
done

case $BLOCK_BUTTON in
    1) echo $((now+break_time)) > /tmp/$filename ;;     # left click
    3) echo $((now+pomodoro_time)) > /tmp/$filename ;;  # right click
    4) echo $((pomodoro_end+5*60)) > /tmp/$filename ;;  # scroll
    5) echo $((pomodoro_end-5*60)) > /tmp/$filename ;;  # scroll
esac

